# Generated by Django 3.0.5 on 2020-07-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200710_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessaryField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='necessary_fields',
        ),
        migrations.AddField(
            model_name='category',
            name='necessary_fields',
            field=models.ManyToManyField(related_name='categories', to='board.NecessaryField'),
        ),
    ]
