# Generated by Django 3.0.5 on 2020-07-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200710_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='necessary_fields',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='board.NecessaryField'),
        ),
    ]
