# Generated by Django 3.0.5 on 2020-07-23 20:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20200710_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='necessaryfield',
            name='type',
            field=models.CharField(choices=[('number', 'число'), ('text', 'текст')], max_length=200),
        ),
    ]
