# Generated by Django 3.0.5 on 2022-07-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20200723_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(default=' ', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(default=' ', editable=False, max_length=1000),
            preserve_default=False,
        ),
    ]
