# Generated by Django 3.0.5 on 2022-08-05 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0012_favoritead'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_sellers', models.ManyToManyField(related_name='favorite_sellers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_favorite_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
