# Generated by Django 3.0.5 on 2022-10-02 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_subway'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minip', models.CharField(max_length=200)),
                ('maxip', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_cities', to='locations.City')),
            ],
        ),
    ]