# Generated by Django 3.0.5 on 2022-10-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_ip_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='subway',
            field=models.ForeignKey(blank=True, null=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='subwayses', to='locations.Subway'),
            preserve_default=False,
        ),
    ]